### ISSUE TITLE
Doesn't read time stamps.

### ISSUE THREAD

**Issue by OmniBlade** [wfr/unshieldv3#1]
Time stamps are stored in the file entries in the toc as a dos date and time stamp in 4 bytes starting at byte 15 IIRC. See https://github.com/OmniBlade/isextract/blob/5adb0af87fb0aaad0b436db0b7e7356947af3ee2/src/isextract.cpp#L124.

**Comment by wfr** [comment]
Thanks for the hint, @OmniBlade. Is it okay for you if I adapt your date/time handling into my code?
I wouldn't want to violate the GPL. This project is Apache 2.0 licensed.
You will get credits of course.

**Comment by OmniBlade** [comment]
Feel free to use it under the Apache 2.0 license.

**Comment by wfr** [comment]
[Fixed](https://github.com/wfr/unshieldv3/pull/2/) better late than never.
